name: CI

on:
  push:
    branches: [staging]

env:
  NODE_VERSION: '17.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04

    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }}"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: echo "ğŸ–¥ï¸ The workflow is now ready to start"

      - name: echo "ğŸ§ 1 - Install dependencies"
        run: |
          yarn install

      - name: echo "ğŸ§ 2 - Run Lint"
        run: |
          yarn lint

      # - name: echo "ğŸ§ 3 - Run tests"
      #   run: |
      #     yarn test

      - name: echo "ğŸ§ 4 - Build files"
        run: |
          yarn build

      - run: echo "ğŸ This job's status is ${{ job.status }}."
